### ISSUE TITLE
Tags in the repository

### ISSUE THREAD

**Issue by DeveloppeurPascal** [okbach/Amazons-Game-Board---DELPHI#4]
Hi

I'm Delphi coder too and code some games with FMX.

To add a little more visibility between Delphi projects here, I use some keywords like "game, delphi, game-development, delphi-source, game-source, delphi-firemonkey, delphi-game".

Could you add some of them (especially "delphi", "delphi-game" and delphi-firemonkey") on your project ?

We have to increase Delphi Community and Delphi Game Community visibility here. ;-)

**Comment by okbach** [comment]
ok thanks
